# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Windows 用 exe をビルド
      run: go build -o obs_wincap_patch.exe main.go
        
    - name: アーティファクトとして exe を保存
      uses: actions/upload-artifact@v4
      with:
       name: obs_wincap_patch_exe
       path: obs_wincap_patch.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            obs_wincap_patch_exe/obs_wincap_patch.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}